# Generated by Django 4.1.2 on 2024-04-30 17:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_alter_forparents_options_alter_forstudents_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forparents',
            name='pub_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
