# Generated by Django 4.1.2 on 2024-04-30 17:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_alter_forparents_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forparents',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
