# Generated by Django 4.1.2 on 2024-04-30 18:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_alter_forparents_pub_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='methodically',
            options={'ordering': ['-pub_date']},
        ),
        migrations.AddField(
            model_name='methodically',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='forstudents',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
